<?php

return [
    'roles' => [
        //modules name
        'roles' => ['read', 'create', 'update', 'delete'],
        'admins' => ['read', 'create', 'update', 'delete'],
        'app_users' => ['read', 'update', 'delete'],
        'org_users' => ['read', 'update', 'delete'],
        'brands' => ['read', 'create', 'update', 'delete'],
        'car_models' => ['read', 'create', 'update', 'delete'],
        'car_classes' => ['read', 'create', 'update', 'delete'],
        'manufacture_countries' => ['read', 'create', 'update', 'delete'],
        'countries' => ['read', 'create', 'update', 'delete'],
        'cities' => ['read', 'create', 'update', 'delete'],
        'areas' => ['read', 'create', 'update', 'delete'],
        'sections' => ['read', 'update'],
        'categories' => ['read', 'create', 'update', 'delete'],
        'sub_categories' => ['read', 'create', 'update', 'delete'],
        'currencies' => ['read', 'create', 'update', 'delete'],
        'payment_methods' => ['read', 'create', 'update', 'delete'],
        'app_sliders' => ['read', 'update'],
        'discount_cards' => ['read', 'create', 'update', 'delete','read-org','update-org','delete-org'],
        'ads' => ['read', 'create', 'update', 'delete'],
        'ad_types' => ['read', 'update'],
        'colors' => ['read', 'create', 'update', 'delete'],
        'special_numbers' => ['read', 'create', 'update', 'delete'],
        'special_numbers_organizations' => ['read', 'create', 'update', 'delete'],
        'agencies' => ['read', 'create', 'update', 'delete'],
        'car_showrooms' => ['read', 'create', 'update', 'delete'],
        'rental_offices' => ['read', 'create', 'update', 'delete'],
        'wenches' => ['read', 'create', 'update', 'delete'],
        'insurance_companies' => ['read', 'create', 'update', 'delete'],
        'brokers' => ['read', 'create', 'update', 'delete'],
        'delivery' => ['read', 'create', 'update', 'delete'],
        'driving_trainers' => ['read', 'create', 'update', 'delete'],
        'fuel_stations' => ['read', 'create', 'update', 'delete'],
        'traffic_clearing_offices' => ['read', 'create', 'update', 'delete'],
        'garages' => ['read', 'create', 'update', 'delete'],
        'technical_inspection_centers' => ['read', 'create', 'update', 'delete'],
        'tire_exchange_centers' => ['read', 'create', 'update', 'delete'],
        'accessories_stores' => ['read', 'create', 'update', 'delete'],
        'car_washes' => ['read', 'create', 'update', 'delete'],
        'mining_centers' => ['read', 'create', 'update', 'delete'],
        'used_vehicles' => ['read', 'create', 'update', 'delete'],

    ],

    'org_roles' => [
        'org_users' => ['read', 'create', 'update', 'delete'],
        'branch_users' => ['read', 'update', 'delete'],
        'org_roles' => ['read', 'create', 'update', 'delete'],
        'general_data' => ['read', 'update','read-org-branch','update-org-branch','create-org-branch','delete-org-branch'],
        'branches' => ['read', 'create', 'update', 'delete'],
        'available_vehicles' => ['read', 'update'],
        'available_products' => ['read', 'update'],
        'available_services' => ['read', 'update'],
        'reserve_vehicles' => ['read', 'update','delete'],
        'tests' => ['read', 'update','delete'],
        'reservations' => ['read', 'update','delete'],
        'rental_office_cars' => ['read', 'create', 'update', 'delete'],
        'cars_properties' => ['read', 'create', 'update', 'delete'],
        'rental_laws' => ['read', 'create', 'update', 'delete'],
        'vehicles' => ['read', 'create', 'update', 'delete'],
        'products' => ['read', 'create', 'update', 'delete'],
        'services' => ['read', 'create', 'update', 'delete'],
        'org_ads' => ['read', 'create', 'update', 'delete'],
        'org_discount_cards' => ['read', 'read-offers', 'update-offers', 'create-offers', 'subscription'],
        'payment_methods' => ['read', 'update'],
        'work_time' => ['read', 'update'],
        'day_offs' => ['read', 'create', 'update', 'delete'],
        'contact' => ['read', 'update'],
        'phones' => ['read', 'create', 'update', 'delete'],
        'reviews' => ['read', 'delete'],

    ]
];
