<?php

return [
    'roles' => [
        //modules name
        'roles' => ['read', 'create', 'update', 'delete'],
        'admins' => ['read', 'create', 'update', 'delete'],
        'brands' => ['read', 'create', 'update', 'delete'],
        'car_models' => ['read', 'create', 'update', 'delete'],
        'car_classes' => ['read', 'create', 'update', 'delete'],
        'manufacture_countries' => ['read', 'create', 'update', 'delete'],
        'countries' => ['read', 'create', 'update', 'delete'],
        'cities' => ['read', 'create', 'update', 'delete'],
        'areas' => ['read', 'create', 'update', 'delete'],
        'sections' => ['read', 'update'],
        'categories' => ['read', 'create', 'update', 'delete'],
        'sub_categories' => ['read', 'create', 'update', 'delete'],
        'currencies' => ['read', 'create', 'update', 'delete'],
        'payment_methods' => ['read', 'create', 'update', 'delete'],
        'app_sliders' => ['read', 'update'],
        'discount_cards' => ['read', 'create', 'update', 'delete'],
        'colors' => ['read', 'create', 'update', 'delete'],
        'special_numbers' => ['read', 'create', 'update', 'delete'],
        'special_numbers_organizations' => ['read', 'create', 'update', 'delete'],
        'agencies' => ['read', 'create', 'update', 'delete'],
        'car_showrooms' => ['read', 'create', 'update', 'delete'],
        'rental_offices' => ['read', 'create', 'update', 'delete'],
        'wenches' => ['read', 'create', 'update', 'delete'],
        'insurance_companies' => ['read', 'create', 'update', 'delete'],
        'brokers' => ['read', 'create', 'update', 'delete'],
        'delivery' => ['read', 'create', 'update', 'delete'],
        'driving_trainers' => ['read', 'create', 'update', 'delete'],
        'fuel_stations' => ['read', 'create', 'update', 'delete'],
        'traffic_clearing_offices' => ['read', 'create', 'update', 'delete'],
        'garages' => ['read', 'create', 'update', 'delete'],
        'technical_inspection_centers' => ['read', 'create', 'update', 'delete'],
        'tire_exchange_centers' => ['read', 'create', 'update', 'delete'],
        'accessories_stores' => ['read', 'create', 'update', 'delete'],
        'car_washes' => ['read', 'create', 'update', 'delete'],
        'mining_centers' => ['read', 'create', 'update', 'delete'],

    ],
];
